apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coco
  labels:
    name: coco
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 15
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        name: coco
    spec:
      containers:
      - image: akshayubhat/dva-auto:latest
        imagePullPolicy: "IfNotPresent"
        name: coco
        env:
        - name: LAUNCH_BY_NAME_detector_coco
          value: "1"
        args:
          - bash
          - -c
          - git reset --hard && git pull && sleep 15  && ./start_container.py