apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dvawebserver
  labels:
    name: dvawebserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: dvawebserver
    spec:
      containers:
      - name: dvawebserver
        image: akshayubhat/dva:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: db-passwords
---
apiVersion: v1
kind: Service
metadata:
  name: dvawebserver
  labels:
    name: dvawebserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    name: dvawebserver
