apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  labels:
    app: postgres
    tier: backend
    role: master
spec:
  selector:
    app: postgres
    tier: backend
    role: master
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/postgres-data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: dGVzdGluZwo=
  password: dGVzdGluZwo=
  database: dGVzdGluZwo=
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 15
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: postgres
        role: master
        tier: backend
    spec:
      containers:
      - image: postgres:9.6-alpine
        imagePullPolicy: "IfNotPresent"
        name: master
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        ports:
        - containerPort: 5432
          name: postgres-master
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresdata-claim
