sudo: required

group: deprecated-2017Q2

language: python

branches:
  only:
  - master

services:
  - docker

script:
  - cd deploy/cpu && docker-compose -f docker-compose-ci.yml up -d
  - sleep 180
  - docker exec -it webserver bash -c 'cd ../tests && python test_ci.py && python test_ci_face.py && python test_ci_search.py'
  - wget --quiet localhost:8000
  - wget --quiet localhost:8000/videos/
  - wget --quiet localhost:8000/status
  - wget --quiet localhost:8000/queries/
  - wget --quiet localhost:8000/queries/1/
  - wget --quiet localhost:8000/tasks/
  - wget --quiet localhost:8000/retrievers/
  - wget --quiet localhost:8000/textsearch/
  - wget --quiet localhost:8000/models/
  - wget --quiet localhost:8000/indexes/
  - wget --quiet localhost:8000/status
  - wget --quiet localhost:8000/api/users/
  - wget --quiet localhost:8000/api/videos/
  - wget --quiet localhost:8000/api/tubes/
  - wget --quiet localhost:8000/api/frames/
  - wget --quiet localhost:8000/api/framelabels/
  - wget --quiet localhost:8000/api/regionlabels/
  - wget --quiet localhost:8000/api/segmentlabels/
  - wget --quiet localhost:8000/api/tubelabels/
  - wget --quiet localhost:8000/api/videolabels/
  - wget --quiet localhost:8000/api/labels/
  - wget --quiet localhost:8000/api/segments/
  - wget --quiet localhost:8000/api/regions/
  - wget --quiet localhost:8000/api/queries/
  - wget --quiet localhost:8000/api/queryresults/
  - wget --quiet localhost:8000/api/indexentries/
  - wget --quiet localhost:8000/api/events/
